# Eliminação de Gauss

### Prof. Pedro Peixoto <ppeixoto@usp.br>

Abril 2022

Referências:

[1] https://www.codesansar.com/numerical-methods/gauss-elimination-method-python-program.htm


In [6]:
import numpy as np
import sys
import time

### O problema Ax=b

In [7]:
# Tamanho do sistema
n = 300

def create_matrix(n):
    # Matriz aumentada A|b
    a = np.zeros((n,n+1))

    # Matriz A
    for i in range(n):
        for j in range(n):
            if (i == j) :
                a[i][j] = 2
            elif (abs(i-j)< 2):
                a[i][j] = -1

    # Vetor b 
    for i in range(n):
        a[i][n] = 1

    print(a)
    return a
    

### O esquema clássico, sem pivotamento

In [12]:
a = create_matrix(n)
x = np.zeros(n)

start_time = time.time()
# Escalonamento
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Ainda não implementei pivotamento :-( ')
        
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]

# Substituição
x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
    
    x[i] = x[i]/a[i][i]
tempo = time.time() - start_time

print("Soma da Solução:", np.sum(x), " Tempo que levou: ", tempo)

# Solução
print('\nSolução: ')
print(x)


[[ 2. -1.  0. ...  0.  0.  1.]
 [-1.  2. -1. ...  0.  0.  1.]
 [ 0. -1.  2. ...  0.  0.  1.]
 ...
 [ 0.  0.  0. ... -1.  0.  1.]
 [ 0.  0.  0. ...  2. -1.  1.]
 [ 0.  0.  0. ... -1.  2.  1.]]
Soma da Solução: 2272550.0000000903  Tempo que levou:  8.135708570480347

Solução: 
[  150.   299.   447.   594.   740.   885.  1029.  1172.  1314.  1455.
  1595.  1734.  1872.  2009.  2145.  2280.  2414.  2547.  2679.  2810.
  2940.  3069.  3197.  3324.  3450.  3575.  3699.  3822.  3944.  4065.
  4185.  4304.  4422.  4539.  4655.  4770.  4884.  4997.  5109.  5220.
  5330.  5439.  5547.  5654.  5760.  5865.  5969.  6072.  6174.  6275.
  6375.  6474.  6572.  6669.  6765.  6860.  6954.  7047.  7139.  7230.
  7320.  7409.  7497.  7584.  7670.  7755.  7839.  7922.  8004.  8085.
  8165.  8244.  8322.  8399.  8475.  8550.  8624.  8697.  8769.  8840.
  8910.  8979.  9047.  9114.  9180.  9245.  9309.  9372.  9434.  9495.
  9555.  9614.  9672.  9729.  9785.  9840.  9894.  9947.  9999. 10050.
 10100. 10149.

### Dá para vetorizar?

In [14]:
a = create_matrix(n)
x = np.zeros(n)


start_time = time.time()

# Escalonamento
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Ainda não implementei pivotamento :-( ')
        
    for j in range(i+1, n):        
        #Vetorizei aqui!
        a[j][:] = a[j][:] - a[j][i]/a[i][i] * a[i][:]

# Substituição
x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    #Vetorizei aqui!
    x[i] = (a[i][n] - np.dot(a[i][i+1:n], x[i+1:n]))/a[i][i]

tempo = time.time() - start_time

print("Soma da Solução:", np.sum(x), " Tempo que levou: ", tempo)

# Solução
print('\nSolução: ')
print(x)

[[ 2. -1.  0. ...  0.  0.  1.]
 [-1.  2. -1. ...  0.  0.  1.]
 [ 0. -1.  2. ...  0.  0.  1.]
 ...
 [ 0.  0.  0. ... -1.  0.  1.]
 [ 0.  0.  0. ...  2. -1.  1.]
 [ 0.  0.  0. ... -1.  2.  1.]]
Soma da Solução: 2272550.0000000903  Tempo que levou:  0.14176011085510254

Solução: 
[  150.   299.   447.   594.   740.   885.  1029.  1172.  1314.  1455.
  1595.  1734.  1872.  2009.  2145.  2280.  2414.  2547.  2679.  2810.
  2940.  3069.  3197.  3324.  3450.  3575.  3699.  3822.  3944.  4065.
  4185.  4304.  4422.  4539.  4655.  4770.  4884.  4997.  5109.  5220.
  5330.  5439.  5547.  5654.  5760.  5865.  5969.  6072.  6174.  6275.
  6375.  6474.  6572.  6669.  6765.  6860.  6954.  7047.  7139.  7230.
  7320.  7409.  7497.  7584.  7670.  7755.  7839.  7922.  8004.  8085.
  8165.  8244.  8322.  8399.  8475.  8550.  8624.  8697.  8769.  8840.
  8910.  8979.  9047.  9114.  9180.  9245.  9309.  9372.  9434.  9495.
  9555.  9614.  9672.  9729.  9785.  9840.  9894.  9947.  9999. 10050.
 10100. 1014

### Dá para vetorizar mais?

Sobraram apenas loops que tem dependências sequenciais, portanto são dificeis de vetorizar. Agora teríamos que pensar em mudanças no algoritmo mesmo...